---
title: "Assignment_Week_1&2_Venkidusamy_KesavAdithya"
Course: "DSC640"
author: "Kesav Adithya Venkidusamy"
date: "2022/06/11"
output: pdf_document
---


```{r libraries}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(ggplot2)
library(tidyverse)

```

# Data Loading
```{r data}

hotdog_df <- read_excel("E:/Personal/Bellevue University/Course/github/dsc640/Week 1&2/hotdog-contest-winners.xlsm")
head(hotdog_df)

# Total number of records present in the data set
nrow(hotdog_df)

## Create Bar Chart

ggplot(hotdog_df, aes(x=Country, y=Dogs_eaten)) +
  geom_bar(stat = "identity", fill = 'steelblue')+
  ggtitle("Number of Hotdogs Eaten by Country")+
  theme_minimal()

```

```{r stackedbar}
# Loadind the 2nd dataset for stacked bar
hdp_df <- read_excel("E:/Personal/Bellevue University/Course/github/dsc640/Week 1&2/hotdog-places.xlsm")

# Showing sample records
head(hdp_df)

## Plotting stacked bar plot
barplot(as.matrix(hdp_df),  main="# of Hot Dog Restaurant by Places",
        xlab="Year",
        ylab="# of Hot Dog Restaurants",
        legend.text =  c('Chicago','Texas','NY'), 
        args.legend = list(x = "topright",bty='n', inset=c(-0.1,0))
        )
```
```{r piechart}

#Read in third file for the pie and donut charts
obama <- read_excel('E:/Personal/Bellevue University/Course/github/dsc640/Week 1&2/obama-approval-ratings.xls')

## Displaying few records
head(obama)

#Set up for pie and donut charts
#Creating smaller dataframe from original dataset
dat <- data.frame(count=c(obama$Approve), category=c(obama$Issue))

#Compute percentages
dat$fraction = dat$count / sum(dat$count)

#Compute the cumulative percentages 
dat$ymax = cumsum(dat$fraction)

#Compute the bottom of each rectangle
dat$ymin = c(0, head(dat$ymax, n=-1))

#Compute label position
dat$labelPosition <- (dat$ymax + dat$ymin) / 2

#Compute a good label
dat$label <- paste0(dat$count)

#Pie chart
ggplot(dat, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() +
  geom_label( x=4, aes(y=labelPosition, label=label), size=3) +
  ggtitle("Approval Ratings by Issue") +
  coord_polar(theta="y") + 
  theme_void() 

#Donut chart
ggplot(dat, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() +
  geom_label( x=4, aes(y=labelPosition, label=label), size=3) +
  ggtitle("Approval Ratings by Issue") +
  coord_polar(theta="y") + 
  theme_void() +
  xlim(c(2, 4))

```
```{r lineplot}

# We will use the same hotdog dataframe for this plot

ggplot(hotdog_df, aes(x=Year, y=Dogs_eaten)) +
  geom_line() + 
  ggtitle("Number of Hotdogs Eaten by Winner by Year")

```
